# This is a basic workflow to help you get started with Actions

name: Danger

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Danger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Generate cache key
          run: /bin/bash scripts/checksum.sh checksum.txt
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      # Runs Danger workflow
      - name: Run Danger
        run: bundle exec danger
